# Generated by Django 5.2.6 on 2025-09-05 18:04

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ragdocument',
            name='support_rag_source__a17ab8_idx',
        ),
        migrations.AddField(
            model_name='ragdocument',
            name='chunk_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ragdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='ragdocument',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ragdocument',
            name='source_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragdocument',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='ragdocument',
            constraint=models.UniqueConstraint(fields=('source_id', 'chunk_hash'), name='unique_source_chunk'),
        ),
    ]
