# Generated by Django 5.2.6 on 2025-09-05 18:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_ragdocument_support_rag_source__a17ab8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
