# Generated by Django 5.2.6 on 2025-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ragdocument_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
