# Generated by Codex CLI to speed up semantic_search

from django.db import migrations
from pgvector.django import HnswIndex
from django.contrib.postgres.indexes import GinIndex

def create_pg_trgm_extension(apps, schema_editor):
    # Ensure pg_trgm is available for trigram index on title
    with schema_editor.connection.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_chatmessage_product_name"),
    ]

    operations = [
        migrations.RunPython(create_pg_trgm_extension, noop),
        migrations.AddIndex(
            model_name="ragdocument",
            index=HnswIndex(
                name="ragdoc_embedding_hnsw_cosine",
                fields=["embedding"],
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="ragdocument",
            index=GinIndex(
                name="ragdoc_title_trgm",
                fields=["title"],
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
