# Generated by Django 5.2.6 on 2025-09-29 17:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_rags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('cat_path', models.JSONField(default=list)),
                ('address', models.JSONField(default=dict)),
                ('price', models.JSONField(default=dict)),
                ('export', models.JSONField(default=dict)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
    ]
