# Generated by Django 5.2.6 on 2025-09-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
