# Generated by Django 5.2.6 on 2025-09-29 17:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_agent', '0002_alter_product_rags_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rags',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
